# Mimir Configuration for T-Mobile Dashboard
# Long-term Prometheus-compatible metrics storage

# Run in single-binary mode for local development
target: all

# Server configuration
server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: info

# Common storage configuration
common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/mimir

# Block storage configuration
blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/blocks
  tsdb:
    dir: /data/mimir/tsdb
  bucket_store:
    sync_dir: /data/mimir/tsdb-sync

# Compactor configuration
compactor:
  data_dir: /data/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

# Distributor configuration
distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

# Ingester configuration
ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

# Store-gateway configuration
store_gateway:
  sharding_ring:
    replication_factor: 1

# Memberlist configuration for single-node
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members: []

# Limits configuration
limits:
  # Allow ingestion of metrics
  ingestion_rate: 10000
  ingestion_burst_size: 200000
  # Query limits
  max_query_lookback: 720h  # 30 days
  max_query_parallelism: 14
  # Cardinality limits
  max_global_series_per_user: 150000
  max_global_series_per_metric: 50000
